# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    binary: ninja-lang
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - "386"

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

release:
  draft: false
  github:
    owner: gravataLonga
    name: ninja
  header: |
    ## New Release {{ .Tag }} ({{ .Date }})
    
    Check changelog for get complete list of new feature, bugfixes and security issues.
  footer: |
    ## Supporting me  
    
    If you like it consider support me at https://github.com/sponsors/gravataLonga.


checksum:
  name_template: 'checksums.txt'

nfpms:
  - vendor: gravataLonga
    package_name: ninja-lang
    homepage: https://ninja.jonathan.pt
    maintainer: Jonathan Fontes <jonathan.alexey16@gmail.com>
    description: Ninja Programming Language
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    id: packages
    file_name_template: "{{ .ConventionalFileName }}"

brews:
  -
    name: ninja-lang
    tap:
      owner: gravataLonga
      name: homebrew-ninja-lang

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Jonathan Fontes
      email: jonathan.alexey16@gmail.com

    commit_msg_template: "New version for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula
    description: "Ninja Programming Language Binary"
    homepage: "https://ninja.jonathan.pt/"
    license: "MIT"

snapshot:
  name_template: "{{.Tag}}"

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gravatalonga/


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^wip:'
      - '^WIP:'
