name: Check dist/

on:
  push:
    branches:
      - main

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go version
  tests:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: '>=1.17.0'
        - run: go test ./...
