name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Build Plugin
        run: go build -buildmode=plugin -o hello.so fixtures/hello.go

      - name: Test
        run: go test -v ./...

      - name: Coverage
        run: go test -coverpkg=./... ./...